### ISSUE TITLE
Bot Crash server Report[BUG] 

### ISSUE THREAD

**Issue by Ki-Tan2934** [ErdbeerbaerLP/DiscordIntegration-Forge#194]
**What happened?**
- Server crashes

**What should happen?**
- Bot should stop

**Steps to reproduce**
- /discord stop

**Version**
- [ ] 1.16.4

**Platform**
- [forge-1.16.4-35.1.29.jar ] Forge

Mod version: 
dcintegration-2.1.0-1.16.jar
**Config file**
- https://paste.ubuntu.com/p/7MTh4MCJSK/

**Crash report if available (use https://hastebin.com)**
- https://paste.ubuntu.com/p/HK72xc6KnN/

**Comment by skythebro** [comment]
Extra info
[08:26:15] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: listeners may not be null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration@5d17d8ae serverStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
java.lang.IllegalArgumentException: listeners may not be null
        at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:64)
        at net.dv8tion.jda.internal.utils.Checks.noneNull(Checks.java:119)
        at net.dv8tion.jda.internal.JDAImpl.removeEventListener(JDAImpl.java:790)
        at de.erdbeerbaerlp.dcintegration.common.Discord.kill(Discord.java:230)
        at de.erdbeerbaerlp.dcintegration.common.Discord.kill(Discord.java:248)
        at de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.serverStopped(DiscordIntegration.java:241)
        at net.minecraftforge.eventbus.ASMEventHandler_19_DiscordIntegration_serverStopped_FMLServerStoppedEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:125)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:683)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

[08:26:15] [Server thread/ERROR] [minecraft/MinecraftServer]: java.lang.IllegalArgumentException: listeners may not be null

**Comment by ErdbeerbaerLP** [comment]
Does this sill happen in this version?
https://erdbeerbaerlp.de/dcintegration-forge-2.2.0-1.16.jar
