### ISSUE TITLE
[BUG] crash if start

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [ErdbeerbaerLP/DiscordIntegration-Forge#204]
**What happened?**
- crash if start spigot/paper 1.16.5 in latest version

**Config file**
-
none

**Crash report if available (use https://hastebin.com)**
-
https://pastebin.com/CDDpjL30

**Comment by jackik1410** [comment]
Ah darn it, seems like I ran into just this issue, at least I presume. Using spigot on 1.16.5


```
[Server thread/ERROR]: Could not load 'plugins\dcintegration-2.1.0-1.16.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/dynmap/DynmapCommonAPIListener
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: org/dynmap/DynmapCommonAPIListener
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.dynmap.DynmapCommonAPIListener
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3011-Spigot-73fb609-d5c5d99]
        ... 7 more```

Is there any current workaround or fix?

**Comment by ErdbeerbaerLP** [comment]
I found the bug and it will be fixed in the next update

**Comment by ErdbeerbaerLP** [comment]
Waiting for project approval...
https://dev.bukkit.org/projects/discordintegration-spigot/files/3308640

(Get the file here if it is not approved when you see this: https://erdbeerbaerlp.de/dcintegration-spigot-2.2.0-1.16.jar )
