### ISSUE TITLE
[BUG][1.15.2] Cannot load overworld

### ISSUE THREAD

**Issue by sharkck** [ErdbeerbaerLP/DiscordIntegration-Forge#206]
I am having the same exact problem as fully detailed here:
https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/80

Every time I add dcintegration-1.3.3-1.15.jar to my mods folder, the server crashes with:
`[1;31m[13:39:36] [Server console handler/ERROR] [minecraft/DedicatedServer]: Caught previously unhandled exception :
java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[server-1.15.2-extra.jar:?] {}
        at net.minecraftforge.common.DimensionManager.initWorld(DimensionManager.java:274) ~[?:?] {re:classloading}
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:208) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_195573_aM(MinecraftServer.java:1513) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:106) ~[?:?] {re:classloading}`

I get this whether I have other mods or not added to the server and whether there is an existing world or not.  That run was with dcintegration as the only mod.  This was using forge-1.15.2-31.2.36.jar as the server.
[debug.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5937418/debug.log)
[latest.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5937419/latest.log)

The same thing happens if I use forge-1.15.2-31.2.47.jar (updated server) as well:

`[13:45:49] [Server console handler/ERROR] [minecraft/DedicatedServer]: Caught previously unhandled exception :
java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[server-1.15.2-extra.jar:?] {}
        at net.minecraftforge.common.DimensionManager.initWorld(DimensionManager.java:274) ~[?:?] {re:classloading}
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:208) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_195573_aM(MinecraftServer.java:1513) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:106) ~[?:?] {re:classloading}`
[debug.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5937427/debug.log)
[latest.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5937428/latest.log)

The really weird thing is that, the last time I ran this server was 09/2020 and everything worked fine.  I initially had changed NOTHING when I went to fire it up today.  Since, I have  updated to the latest version of Java.  Currently, this machine is running Windows 10 professional build 1903... maybe there's something wrong due to not being on the latest Windows updates?  Will provide an update after installing OS updates.

**Comment by sharkck** [comment]
Note: I also tried downgrading to the previous version of dcintegration and got the same results.

**Comment by sharkck** [comment]
Updated to Windows version 1909.  Same issue.

**Comment by cl8n** [comment]
on the offchance this helps, I found that I only got this error when running dcintegration and https://www.curseforge.com/minecraft/mc-mods/performant together. removing either mod stopped it from crashing

**Comment by ErdbeerbaerLP** [comment]
Actually closing this as I no longer support 1.15.

If this still happens in 1.16 just re-open it and I will try to fix it again
