### ISSUE TITLE
Minecraft chat sending messages to discord, but not vice versa. 

### ISSUE THREAD

**Issue by CandyPillager** [ErdbeerbaerLP/DiscordIntegration-Forge#221]
**What happened?**
-so I setup the mod for a friend's server. I did every step in the guide. (Everything worked wonders on my own 1.12 server, his server is in 1.16.4), all the Minecraft Chat's messages got sent to the discord channel, but, when saying something in the discord channel it doesn't show up in minecraft.. I didn't have this problem in 1.12. I can't do any commands either.

**What should happen?**
- It should send the discord messages to minecraft chat if I setup everything correctly. 

**Steps to reproduce**
- install the mod on 1.16.4 server, with my friend's modpack (Named "Cameo's Magic Modpack" on Curseforge)
- 

**Version**
-
-  1.16

**Platform**
-
- Forge

Mod version: 
2.1.0
**Config file**
-https://paste.gg/p/anonymous/b222b095fa734817a99f5f86842ee93c
if that's not good, here's the uploaded version.
[Discord-Integration.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/6043179/Discord-Integration.txt)

**Comment by jerbear2008** [comment]
Same! Please help!

**Comment by Zolfax** [comment]
Any update on this one here?
Could it be reproduced?

**Comment by ErdbeerbaerLP** [comment]
I am unable to reproduce that. I tried using the exact same config file but with my token and channels and it works.

I would recommend checking your discord bot's permissions

**Comment by Zolfax** [comment]
Can confirm.
It has to do something with the discord bot permissions!

I gave the bot Discord Administrator on my server and it worked like a charm.

**Comment by DrToxic** [comment]
Can confirm, using 1.16.2 for Forge (Also modded with Vivecraft)
yes, I know I need to update, but with comments above, version appears not to be too significant.
I only noticed this today while moving servers from one ESXi box to another.

**Comment by CritFlaw** [comment]
Ok since nobody else is pasting their configs, here is mine with the token and cannel ID taken out for safety: https://pastebin.com/BqFKv431

Even with bot having admin, this does not work both ways, only Minecraft -> Discord

**Comment by leo60228** [comment]
For me, this was a result of the bot not having the Manage Messages permission. I don't see any reason for the bot to need it.

**Comment by CameoDaManeo** [comment]
Henlo, yes. It is I, OP's friend, who also owns the server and is still having troubles with Discord -> Minecraft messaging.

I've tried all of these fixes. I've configured it in accordance with the manual and I've given the bot full admin abilities.

If there is any other information you guys may need, please let me know and I will provide them.

**Comment by CameoDaManeo** [comment]
Henlo, yes. It is I, OP's friend, again.

I have managed to solve the issue. The solution was to give the bot admin permissions. Thank you all and have a nice day!

**Comment by FakeDomi** [comment]
https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/master/src/main/java/de/erdbeerbaerlp/dcintegration/common/Discord.java#L175

you need to grant the bot all of those:
Permission.MESSAGE_READ, Permission.MESSAGE_WRITE, Permission.MESSAGE_EMBED_LINKS, Permission.MESSAGE_MANAGE
or the discord -> minecraft bridge just won't work

@ErdbeerbaerLP you could improve the error log, it does not show what permissions are actually needed
this was all that was being logged

```
[10May2021 13:21:37.536] [Discord Integration Launch Thread/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.common.Discord:run:176]: ERROR! Bot does not have all permissions to work!
[10May2021 13:21:37.539] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: java.lang.IllegalArgumentException: listeners may not be null
[10May2021 13:21:37.540] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:64)
[10May2021 13:21:37.540] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.dv8tion.jda.internal.utils.Checks.noneNull(Checks.java:119)
[10May2021 13:21:37.540] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.dv8tion.jda.internal.JDAImpl.removeEventListener(JDAImpl.java:790)
[10May2021 13:21:37.541] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at de.erdbeerbaerlp.dcintegration.common.Discord.kill(Discord.java:230)
[10May2021 13:21:37.542] [Discord Integration Launch Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at de.erdbeerbaerlp.dcintegration.common.Discord.run(Discord.java:177)
```

**Comment by CritFlaw** [comment]
Yeah so this ended up working, but I have absolutely no idea what changed, it just started working at some point

**Comment by ErdbeerbaerLP** [comment]
Still an bug? If yes, simply re-open ;)
