### ISSUE TITLE
Crash upon world load

### ISSUE THREAD

**Issue by PQxDev01** [ErdbeerbaerLP/DiscordIntegration-Forge#233]
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at de.erdbeerbaerlp.dcintegration.common.storage.PlayerLinkController.getSettings(PlayerLinkController.java:244) ~[?:2.1.0] {re:classloading}
	at de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.advancement(DiscordIntegration.java:150) ~[?:2.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_139_DiscordIntegration_advancement_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2583/1160642499.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1059) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:213) ~[?:?] {re:classloading}
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72) ~[?:?] {re:classloading}
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234804_a_(SourceFile:54) ~[?:?] {re:classloading}
	at net.minecraft.advancements.criterion.InventoryChangeTrigger.func_234803_a_(SourceFile:50) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71111_a(ServerPlayerEntity.java:942) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcreativity.mixins.json:MixinServerPlayerEntity,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.sync_attacker_yaw.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.obsidian_tears.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:A}
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:129) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:babel.mixins.json:ContainerMixin,pl:mixin:APP:notenoughcreativity.mixins.json:AccessorScreenHandler,pl:mixin:A}
	at net.minecraft.inventory.container.Container.func_75132_a(Container.java:99) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:babel.mixins.json:ContainerMixin,pl:mixin:APP:notenoughcreativity.mixins.json:AccessorScreenHandler,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71116_b(ServerPlayerEntity.java:332) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcreativity.mixins.json:MixinServerPlayerEntity,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.sync_attacker_yaw.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.obsidian_tears.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:A}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:230) ~[?:?] {re:mixin,re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$20681/1646224797.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by Tander** [comment]
The same thing. Happens when i'm trying to start single player with this mod.

Crashlog:
https://pastebin.com/qyjUe9UX

**Comment by Tander** [comment]
On dedicated server it seems to work properly though, so it's singleplayer issue. But please fix, as it's more convenient for testing configurations.

**Comment by ErdbeerbaerLP** [comment]
This mod is for servers only, but I will still fix that as if you accidentally install it on client, it should do nothing at all...
