### ISSUE TITLE
To many dimensions breaks /tps[BUG] 

### ISSUE THREAD

**Issue by Ki-Tan2934** [ErdbeerbaerLP/DiscordIntegration-Forge#257]
**What happened?**
-Does not display the tps

**What should happen?**
-Display the TPS

**Steps to reproduce**
- Have around 20 dimensions (Rftools dim will makes loads)
- Do /tps in the commands channel
- Nothing will display

- /Forge tps does still work in the console
**Version**
- Any

**Platform**
-  Forge

Mod version: 
- Any

**Comment by jeremiahwinsley** [comment]
Additional info - this message is displayed in console:
```
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: java.lang.IllegalArgumentException: Content may not exceed 2000 characters!
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at dcshadow.club.minnced.discord.webhook.send.WebhookMessageBuilder.setContent(WebhookMessageBuilder.java:182)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord$DCMessage.buildWebhookMessage(Discord.java:960)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:366)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:409)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:435)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord.sendMessage(Discord.java:431)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord$2.lambda$run$0(Discord.java:195)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[21:35:52] [[DC INTEGRATION] Discord Command Message Sender/INFO] [STDERR/]: [de.erdbeerbaerlp.dcintegration.Discord:sendMessage:379]: 	at de.erdbeerbaerlp.dcintegration.Discord$2.run(Discord.java:191)
```

**Comment by Ki-Tan2934** [comment]
So bot needs to be able to do multi messages

**Comment by ErdbeerbaerLP** [comment]
Can you try if the message splitting works with this version?
https://erdbeerbaerlp.de/dcintegration-forge-2.2.0-1.16.jar

**Comment by Reinitialized** [comment]
Can confirm 2.2.0 fixes issue. Bot now appropriately spams my channel with 2000+ character responses :)
