### ISSUE TITLE
[BUG]  messeges dotn show up in discord or in minecraft

### ISSUE THREAD

**Issue by zaze06** [ErdbeerbaerLP/DiscordIntegration-Forge#289]
**What happened?**
- somthing is sent in minecraft chat it doesn't show up in discord and same when the message is sent in discord

**What should happen?**
- the message is displaid in ether Minecraft or discord

**Steps to reproduce**
- install the mod
- set up bot and give it permisins as it needs
- start server
- join server
- type something in chat 
- get disappointed because the message is not displayed in discord

**Version**
- 
- [5] 1.16

**Platform**
-
- [36.1.31] Forge

Mod version: 

**Config file**
- https://gist.github.com/zaze06/f0ffec354e44044d797a546dcd27fb8e
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
- I use mohist server becus i have some plugins too
- I get the the server starts how many is online and when someone joins but not the messeges
- I have not given the virtual player op yet

**Comment by zaze06** [comment]
/say works
also i use the plugin essentials

**Comment by ErdbeerbaerLP** [comment]
HMm..

Does the same happen with the spigot version?

**Comment by zaze06** [comment]
haven't tried

**Comment by zaze06** [comment]
im mising the config folder for the plugin

**Comment by ErdbeerbaerLP** [comment]
It's in /plugins/DiscordIntegration/config.toml
You can just copy the forge one there (and rename it accordingly) and it *should* work

**Comment by zaze06** [comment]
yes but not when the plugin get loaded

**Comment by ErdbeerbaerLP** [comment]
🤔 

Looks like I need to make an local mohist instance myself to test it

**Comment by zaze06** [comment]
hears the error
```
27.06 09:03:49 [Server] ERROR Could not load 'plugins\dcintegration-spigot-2.1.1-1.16.jar' in folder 'plugins'
27.06 09:03:49 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/dynmap/DynmapCommonAPIListener
27.06 09:03:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:150) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[forge:7e29f765-296df566-9fb885e8]
27.06 09:03:49 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881) ~[forge:7e29f765-296df566-9fb885e8]
27.06 09:03:49 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:653) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[forge:?]
27.06 09:03:49 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[forge:7e29f765-296df566-9fb885e8]
27.06 09:03:49 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1829) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1676) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:887) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178) ~[?:?]
27.06 09:03:49 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:870) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:864) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:850) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:770) ~[?:?]
27.06 09:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
27.06 09:03:50 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
27.06 09:03:50 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/dynmap/DynmapCommonAPIListener
27.06 09:03:50 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
27.06 09:03:50 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
27.06 09:03:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:74) ~[forge:?]
27.06 09:03:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:146) ~[forge:?]
27.06 09:03:50 [Server] INFO ... 26 more
27.06 09:03:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.dynmap.DynmapCommonAPIListener
27.06 09:03:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[forge:?]
27.06 09:03:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:106) ~[forge:?]
27.06 09:03:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
27.06 09:03:50 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
27.06 09:03:50 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
27.06 09:03:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:74) ~[forge:?]
27.06 09:03:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:146) ~[forge:?]
```

**Comment by ErdbeerbaerLP** [comment]
oh.... wait... 

Why does it still need dynmap :/ It should have been fixed.

For testing, can you install the dynmap plugin, too? (you don't need to configure it)

**Comment by ErdbeerbaerLP** [comment]
Ah you use an older version

try this: https://www.curseforge.com/minecraft/bukkit-plugins/discordintegration-spigot/files/3308640

this one is without dynmap requirement

**Comment by zaze06** [comment]
ok thx but we will probobly keep dynmap tho :) but I will use that new one instead

**Comment by zaze06** [comment]
hmm i get this and the server craches
`Caused by 1: java.lang.RuntimeException: java.lang.IllegalStateException: Invalid value on line 5: botToken = TOKEN"`
then that row in the config looks like this
`botToken = "TOKEN"`

**Comment by zaze06** [comment]
but i get that from the forge mod when the mod is deleted from the server?

**Comment by zaze06** [comment]
can you tack a look at this crach report from FML and tell me how to make so it don't run the forge version anymore
https://hastebin.com/igulosugid.properties

**Comment by ErdbeerbaerLP** [comment]
you prevent the forge version from running by simply moving the mod jar out of the mods folder

**Comment by zaze06** [comment]
yes but the mods simply dont exist on the server

**Comment by zaze06** [comment]
ok this is scufed i removed the mod, the plugin and its config and I still get the same crash report

**Comment by zaze06** [comment]
im trying to get help from mohist

**Comment by ErdbeerbaerLP** [comment]
Good idea. Because it is not normal that deleting does not prevent it from loading. Never seen such an bug before

**Comment by zaze06** [comment]
me nether

**Comment by zaze06** [comment]
o well rn the server is stuck..... so discord integration needs to wait

**Comment by zaze06** [comment]
so the curent status is that we cant start any server type so I close this issue for now
