### ISSUE TITLE
[BUG] Exception in thread "Discord Integration Launch Thread" 1.12.2

### ISSUE THREAD

**Issue by UrbanSide** [ErdbeerbaerLP/DiscordIntegration-Forge#290]
```
[11:06:49] [Discord Integration Launch Thread/WARN] []: Exception in thread "Discord Integration Launch Thread" 
[11:06:49] [Discord Integration Launch Thread/WARN] []: net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: javax.net.ssl.SSLHandshakeException
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:256)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1929)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at de.erdbeerbaerlp.dcintegration.common.Discord.run(Discord.java:152)
[11:06:49] [Discord Integration Launch Thread/WARN] []: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealConnection.connect(RealConnection.kt:209)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at dcshadow.okhttp.internal.connection.RealCall.execute(RealCall.kt:154)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:200)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:123)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.validator.Validator.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	... 36 more
[11:06:49] [Discord Integration Launch Thread/WARN] []: Caused by: java.security.cert.CertPathValidatorException: validity check failed
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at java.security.cert.CertPathValidator.validate(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	... 42 more
[11:06:49] [Discord Integration Launch Thread/WARN] []: Caused by: java.security.cert.CertificateNotYetValidException: NotBefore: Tue Jan 19 03:00:00 MSK 2021
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.x509.CertificateValidity.valid(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at sun.security.provider.certpath.BasicChecker.check(Unknown Source)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	... 47 more
[11:06:49] [Discord Integration Launch Thread/WARN] []: Caused by: net.dv8tion.jda.api.exceptions.ContextException
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:623)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:256)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1929)
[11:06:49] [Discord Integration Launch Thread/WARN] []: 	at de.erdbeerbaerlp.dcintegration.common.Discord.run(Discord.java:152)
[11:06:53] [Server thread/TRACE] [FML]: Sent event FMLPreInitializationEvent to mod dcintegration
[11:06:53] [Server thread/DEBUG] [FML]: Bar Step: PreInitialization - Discord Integration took 6.234s
[11:06:53] [Server thread/DEBUG] [FML]: Bar Finished: PreInitialization took 62.701s
```

**Comment by ErdbeerbaerLP** [comment]
It looks like your time and date on the server is invalid. 
It is likely set before 19th January 2021 preventing an HTTPS connection to discord
`CertificateNotYetValidException: NotBefore: Tue Jan 19 03:00:00 MSK 2021`
