### ISSUE TITLE
[BUG] 1.16.5 crash on startup

### ISSUE THREAD

**Issue by GreatSymphonia** [ErdbeerbaerLP/DiscordIntegration-Forge#317]
**What happened?**
- Impossible to launch the server

**What should happen?**
- The server should launch

**Steps to reproduce**
- Launch the server
- 

**Version**
-
- [ ] 1.12
- [x] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 

**Config file**
- [Discord-Integration.txt](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/files/6983916/Discord-Integration.txt)

*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-
        

> Crash Report UUID: 8a2c3325-3b8f-4b75-b3b2-e2e8919b40a1
>         [Psi] Active spell: None[18:24:23] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
>         Discord Integration (dcintegration) encountered an error during the sided_setup event phase
> §7java.lang.NoClassDefFoundError: de/erdbeerbaerlp/dcintegration/common/discordCommands/CommandRegistry
> ]
>         at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
>         at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:244) ~[forge:?] {re:classloading}
>         at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:213) ~[forge:?] {re:classloading}
>         at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge:?] {re:classloading}
>         at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
>         at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.0.jar:36.2] {}
>         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
>         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
>         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
>         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
>         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
>         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.0.jar:?] {}
>         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.0.jar:?] {}
>         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.0.jar:?] {}

**Additional info**
- Using the version 1.7.6 of the modpack All The Mods 6 (1.16.5)

**Comment by GreatSymphonia** [comment]
For now, I use an old version of the bot (1.3.4 I think), it rtuns but has not the latest features
